# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: happily plant powered
title: happily plant powered
email: contact@happilyplantpowered.com
language: en-gb
date_format: "%d.%m.%Y"
show_hero: true
description: >- # this means to ignore newlines until "baseurl:"
  A great collection of inspiring easy and awesome vegan recipes!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://happilyplantpowered.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
instagram_username: happily.plant.powered
google_analytics: "UA-174430278-1"
permalink: /:categories/:year/:month/:day/:title

# Build settings
destination: docs
theme: jekflix
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  recipes:
    output: true
    permalink: /:collection/:title
  recipe_categories:
    output: false

sass:
  style: compressed

menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Recipes
    url: /recipes

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: true

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: happilyplantpowered

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
